print ('===============DESAFIO 03===============')
num1 = input ('Digite o primeiro número: ')
num2 = input ('Digite o segundo número: ')
soma = int (num1) + int (num2)
#print ('A soma é {}'.format(soma))
print('A soma entre {} e {} vale {}'.format(num1, num2, soma))